<?php 
/******************************************************************
    (被functions.php主函数引用.)
    作用: 根据Advanced Custom Fields插件, 手动注册一系列自定义字段.
    优点: 字段结构与主题密切相关,以文件形式存储于主体中便于同步.
    ================================================
      Advanced Custom Field (ACF)插件的前端使用方法
    ================================================
    the_field()用来显示字段值, get_field()用来返回字段值.两者的参数是一模一样的.
    the_field($field_id [,$post_id])
    $field_id为在acf后台中,该字段的名称(即id).
    如果the_field()函数用于have_posts()主循环中,则无需指定$post_id.
    但是如果想随时随地获取某一特定页面中的自定义字段,则需要制定post_id.
    这个id在打开该页面的编辑页面时,url中有显示.
    例子:
    <img src="<?php the_field('logo', '46'); ?>">
    这样就可以获取到id为46的页面中的logo地址了
    ================================================================
      以下将注册一系列自定义字段 (从ACF中的"导出到php"复制而来)
*******************************************************************/
/*决定是否在后台显示插件管理的入口(true:隐藏 false:显示)*/
// define( 'ACF_LITE', true );

if(function_exists("register_field_group"))
{
	register_field_group(array (
		'id' => 'acf_%e6%a8%a1%e5%9d%97-%e4%bc%81%e4%b8%9a%e7%89%b9%e8%89%b2',
		'title' => '模块 - 企业特色',
		'fields' => array (
			array (
				'key' => 'field_56c85b74494fc',
				'label' => '企业特色简介',
				'name' => '',
				'type' => 'tab',
			),
			array (
				'key' => 'field_56c85b73242fa',
				'label' => '企业特色标题 feature_title',
				'name' => 'feature_title',
				'type' => 'text',
				'default_value' => 'Feature Intro Title',
				'placeholder' => '请输入标题',
				'prepend' => '',
				'append' => '',
				'formatting' => 'none',
				'maxlength' => 20,
			),
			array (
				'key' => 'field_56c85b737b1ae',
				'label' => '企业特色简介 feature_intro',
				'name' => 'feature_intro',
				'type' => 'wysiwyg',
				'default_value' => '',
				'toolbar' => 'full',
				'media_upload' => 'no',
			),
			array (
				'key' => 'field_56c85b74709ed',
				'label' => '企业特色1',
				'name' => '',
				'type' => 'tab',
			),
			array (
				'key' => 'field_56c85b739e81f',
				'label' => '特色标题1 feature_title_1',
				'name' => 'feature_title_1',
				'type' => 'text',
				'default_value' => 'Feature Title',
				'placeholder' => '请输入一个企业特色的名字',
				'prepend' => '',
				'append' => '',
				'formatting' => 'none',
				'maxlength' => '',
			),
			array (
				'key' => 'field_56c85b74b8e3e',
				'label' => '特色图标1 feature_icon_code_1',
				'name' => 'feature_icon_code_1',
				'type' => 'text',
				'instructions' => '图标代码对应的图标是什么样子在这里查询：http://ionicons.com/',
				'default_value' => 'ion-star',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'none',
				'maxlength' => '',
			),
			array (
				'key' => 'field_56c85b7488cab',
				'label' => '特色内容1 feature_content_1',
				'name' => 'feature_content_1',
				'type' => 'text',
				'default_value' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Voluptatum, sint.',
				'placeholder' => '请输入企业特色的简介',
				'prepend' => '',
				'append' => '',
				'formatting' => 'none',
				'maxlength' => 100,
			),
			array (
				'key' => 'field_56c85b74187b0',
				'label' => '企业特色2',
				'name' => '',
				'type' => 'tab',
			),
			array (
				'key' => 'field_56c85b73b054b',
				'label' => '特色标题2 feature_title_2',
				'name' => 'feature_title_2',
				'type' => 'text',
				'default_value' => 'Feature Title',
				'placeholder' => '请输入一个企业特色的名字',
				'prepend' => '',
				'append' => '',
				'formatting' => 'none',
				'maxlength' => '',
			),
			array (
				'key' => 'field_56c85b74df38f',
				'label' => '特色图标2 feature_icon_code_2',
				'name' => 'feature_icon_code_2',
				'type' => 'text',
				'instructions' => '图标代码对应的图标是什么样子在这里查询：http://ionicons.com/',
				'default_value' => 'ion-star',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'none',
				'maxlength' => '',
			),
			array (
				'key' => 'field_56c85b73d66b4',
				'label' => '特色内容2 feature_content_2',
				'name' => 'feature_content_2',
				'type' => 'text',
				'default_value' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Voluptatum, sint.',
				'placeholder' => '请输入企业特色的简介',
				'prepend' => '',
				'append' => '',
				'formatting' => 'none',
				'maxlength' => 100,
			),
			array (
				'key' => 'field_56c85b7433d37',
				'label' => '企业特色3',
				'name' => '',
				'type' => 'tab',
			),
			array (
				'key' => 'field_56c85b73c8bf1',
				'label' => '特色标题3 feature_title_3',
				'name' => 'feature_title_3',
				'type' => 'text',
				'default_value' => 'Feature Title',
				'placeholder' => '请输入一个企业特色的名字',
				'prepend' => '',
				'append' => '',
				'formatting' => 'none',
				'maxlength' => '',
			),
			array (
				'key' => 'field_56c85b750c0af',
				'label' => '特色图标3 feature_icon_code_3',
				'name' => 'feature_icon_code_3',
				'type' => 'text',
				'instructions' => '图标代码对应的图标是什么样子在这里查询：http://ionicons.com/',
				'default_value' => 'ion-star',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_56c85b73eed59',
				'label' => '特色内容3 feature_content_3',
				'name' => 'feature_content_3',
				'type' => 'text',
				'default_value' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Voluptatum, sint.',
				'placeholder' => '请输入企业特色的简介',
				'prepend' => '',
				'append' => '',
				'formatting' => 'none',
				'maxlength' => 100,
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'page',
					'operator' => '==',
					'value' => '46',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
		),
		'options' => array (
			'position' => 'normal',
			'layout' => 'default',
			'hide_on_screen' => array (
				0 => 'the_content',
				1 => 'excerpt',
				2 => 'custom_fields',
				3 => 'discussion',
				4 => 'comments',
				5 => 'slug',
				6 => 'author',
				7 => 'format',
				8 => 'featured_image',
				9 => 'categories',
				10 => 'tags',
			),
		),
		'menu_order' => 0,
	));
	register_field_group(array (
		'id' => 'acf_%e6%a8%a1%e5%9d%97-%e5%85%a8%e7%ab%99',
		'title' => '模块 - 全站',
		'fields' => array (
			array (
				'key' => 'field_56c858fe6c762',
				'label' => '登录页面Logo',
				'name' => 'login-logo',
				'type' => 'image',
				'instructions' => '请务必适当调整Logo尺寸大小, 以适应展现效果.',
				'save_format' => 'url',
				'preview_size' => 'full',
				'library' => 'all',
			),
			array (
				'key' => 'field_56c858fde1274',
				'label' => '网站Logo',
				'name' => 'logo',
				'type' => 'image',
				'instructions' => '图像格式应为png格式.
	请务必适当调整Logo尺寸大小, 以适应展现效果.',
				'save_format' => 'url',
				'preview_size' => 'full',
				'library' => 'all',
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'page',
					'operator' => '==',
					'value' => '46',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
		),
		'options' => array (
			'position' => 'normal',
			'layout' => 'default',
			'hide_on_screen' => array (
				0 => 'the_content',
				1 => 'excerpt',
				2 => 'custom_fields',
				3 => 'discussion',
				4 => 'comments',
				5 => 'slug',
				6 => 'author',
				7 => 'format',
				8 => 'featured_image',
				9 => 'categories',
				10 => 'tags',
			),
		),
		'menu_order' => 0,
	));
	register_field_group(array (
		'id' => 'acf_%e6%a8%a1%e5%9d%97-%e5%88%86%e7%b1%bb%e5%9b%be%e5%83%8f',
		'title' => '模块 - 分类图像',
		'fields' => array (
			array (
				'key' => 'field_56c5a1d49d1f5',
				'label' => '外部链接 outside-link',
				'name' => 'outside-link',
				'type' => 'text',
				'instructions' => '一般用于商品等外部(淘宝/京东)跳转链接',
				'default_value' => '',
				'placeholder' => '请输入该项目的外部链接',
				'prepend' => '',
				'append' => '',
				'formatting' => 'none',
				'maxlength' => '',
			),
			array (
				'key' => 'field_56bceaa47f0e2',
				'label' => '分类图 taxonomy-image',
				'name' => 'taxonomy-image',
				'type' => 'image',
				'save_format' => 'url',
				'preview_size' => 'full',
				'library' => 'all',
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'ef_taxonomy',
					'operator' => '==',
					'value' => 'all',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
		),
		'options' => array (
			'position' => 'normal',
			'layout' => 'default',
			'hide_on_screen' => array (
			),
		),
		'menu_order' => 0,
	));
	register_field_group(array (
		'id' => 'acf_%e6%a8%a1%e5%9d%97-%e6%88%91%e4%bb%ac%e7%9a%84%e5%ae%a2%e6%88%b7',
		'title' => '模块 - 我们的客户',
		'fields' => array (
			array (
				'key' => 'field_56bde6cd4318f',
				'label' => '客户展示标题 clients_title',
				'name' => 'clients_title',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'none',
				'maxlength' => 17,
			),
			array (
				'key' => 'field_56bb1f1d2b366',
				'label' => '标语',
				'name' => 'banner',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => '请输入关于客户的简单标语',
				'prepend' => '',
				'append' => '',
				'formatting' => 'none',
				'maxlength' => '',
			),
			array (
				'key' => 'field_56bb1da335bc1',
				'label' => '客户Logo 1 client_logo_1',
				'name' => 'client_logo_1',
				'type' => 'image',
				'instructions' => '图像尺寸应为100×100,图像格式应为背景透明的png图片',
				'save_format' => 'url',
				'preview_size' => 'full',
				'library' => 'all',
			),
			array (
				'key' => 'field_56bb2a672175c',
				'label' => '客户Logo 2 client_logo_2',
				'name' => 'client_logo_2',
				'type' => 'image',
				'instructions' => '图像尺寸应为100×100,图像格式应为背景透明的png图片',
				'save_format' => 'url',
				'preview_size' => 'full',
				'library' => 'all',
			),
			array (
				'key' => 'field_56bb2a662175b',
				'label' => '客户Logo 3',
				'name' => 'client_logo_3',
				'type' => 'image',
				'instructions' => '图像尺寸应为100×100,图像格式应为背景透明的png图片',
				'save_format' => 'url',
				'preview_size' => 'full',
				'library' => 'all',
			),
			array (
				'key' => 'field_56bb2a662175a',
				'label' => '客户Logo 4',
				'name' => 'client_logo_4',
				'type' => 'image',
				'instructions' => '图像尺寸应为100×100,图像格式应为背景透明的png图片',
				'save_format' => 'url',
				'preview_size' => 'full',
				'library' => 'all',
			),
			array (
				'key' => 'field_56bb2a6521759',
				'label' => '客户Logo 5',
				'name' => 'client_logo_5',
				'type' => 'image',
				'instructions' => '图像尺寸应为100×100,图像格式应为背景透明的png图片',
				'save_format' => 'url',
				'preview_size' => 'full',
				'library' => 'all',
			),
			array (
				'key' => 'field_56bb2a6521758',
				'label' => '客户Logo 6',
				'name' => 'client_logo_6',
				'type' => 'image',
				'instructions' => '图像尺寸应为100×100,图像格式应为背景透明的png图片',
				'save_format' => 'url',
				'preview_size' => 'full',
				'library' => 'all',
			),
			array (
				'key' => 'field_56bb2a6421757',
				'label' => '客户Logo 7',
				'name' => 'client_logo_7',
				'type' => 'image',
				'instructions' => '图像尺寸应为100×100,图像格式应为背景透明的png图片',
				'save_format' => 'url',
				'preview_size' => 'full',
				'library' => 'all',
			),
			array (
				'key' => 'field_56bb2a6421756',
				'label' => '客户Logo 8',
				'name' => 'client_logo_8',
				'type' => 'image',
				'instructions' => '图像尺寸应为100×100,图像格式应为背景透明的png图片',
				'save_format' => 'url',
				'preview_size' => 'full',
				'library' => 'all',
			),
			array (
				'key' => 'field_56bb2a6321755',
				'label' => '客户Logo 9',
				'name' => 'client_logo_9',
				'type' => 'image',
				'instructions' => '图像尺寸应为100×100,图像格式应为背景透明的png图片',
				'save_format' => 'url',
				'preview_size' => 'full',
				'library' => 'all',
			),
			array (
				'key' => 'field_56bb2a5c21754',
				'label' => '客户Logo 10',
				'name' => 'client_logo_10',
				'type' => 'image',
				'instructions' => '图像尺寸应为100×100,图像格式应为背景透明的png图片',
				'save_format' => 'url',
				'preview_size' => 'full',
				'library' => 'all',
			),
			array (
				'key' => 'field_56c61451acb83',
				'label' => '客户Logo 11',
				'name' => 'client_logo_11',
				'type' => 'image',
				'instructions' => '图像尺寸应为100×100,图像格式应为背景透明的png图片',
				'save_format' => 'url',
				'preview_size' => 'full',
				'library' => 'all',
			),
			array (
				'key' => 'field_56c6144eacb82',
				'label' => '客户Logo 12',
				'name' => 'client_logo_12',
				'type' => 'image',
				'instructions' => '图像尺寸应为100×100,图像格式应为背景透明的png图片',
				'save_format' => 'url',
				'preview_size' => 'full',
				'library' => 'all',
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'page',
					'operator' => '==',
					'value' => '46',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
		),
		'options' => array (
			'position' => 'normal',
			'layout' => 'default',
			'hide_on_screen' => array (
				0 => 'permalink',
				1 => 'the_content',
				2 => 'excerpt',
				3 => 'custom_fields',
				4 => 'discussion',
				5 => 'comments',
				6 => 'slug',
				7 => 'author',
				8 => 'format',
				9 => 'featured_image',
				10 => 'categories',
				11 => 'tags',
			),
		),
		'menu_order' => 0,
	));
	register_field_group(array (
		'id' => 'acf_%e6%a8%a1%e5%9d%97-%e9%a1%b5%e8%84%9a',
		'title' => '模块 - 页脚',
		'fields' => array (
			array (
				'key' => 'field_56c8594cdc6e9',
				'label' => '页脚标语 - 题目 footer-banner-title',
				'name' => 'footer-banner-title',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'none',
				'maxlength' => '',
			),
			array (
				'key' => 'field_56c8598fdc6ea',
				'label' => '页脚标语 - 正文 footer-banner-content',
				'name' => 'footer-banner-content',
				'type' => 'wysiwyg',
				'default_value' => '',
				'toolbar' => 'full',
				'media_upload' => 'yes',
			),
			array (
				'key' => 'field_56c859bedc6eb',
				'label' => '页脚标语 - 按钮文字 footer-banner-link-text',
				'name' => 'footer-banner-link-text',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'none',
				'maxlength' => '',
			),
			array (
				'key' => 'field_56c859ecdc6ec',
				'label' => '页脚标语 - 按钮链接 footer-bannre-link',
				'name' => 'footer-bannre-link',
				'type' => 'page_link',
				'post_type' => array (
					0 => 'post',
					1 => 'page',
					2 => 'outfits',
					3 => 'outdoors',
					4 => 'services',
				),
				'allow_null' => 0,
				'multiple' => 0,
			),
			array (
				'key' => 'field_56c85a5adc6ed',
				'label' => '页脚视频 - 缩略图 footer-video-thumbnail',
				'name' => 'footer-video-thumbnail',
				'type' => 'image',
				'save_format' => 'url',
				'preview_size' => 'medium',
				'library' => 'all',
			),
			array (
				'key' => 'field_56c85a8edc6ee',
				'label' => '页脚视频 - 链接 footer-video-link',
				'name' => 'footer-video-link',
				'type' => 'page_link',
				'post_type' => array (
					0 => 'post',
					1 => 'outdoors',
					2 => 'services',
				),
				'allow_null' => 0,
				'multiple' => 0,
			),
			array (
				'key' => 'field_56c9f59bcead3',
				'label' => '页脚版权',
				'name' => 'footer-copyright',
				'type' => 'wysiwyg',
				'default_value' => '© 2016 意动户外. All rights reserved.',
				'toolbar' => 'full',
				'media_upload' => 'yes',
			),
			array (
				'key' => 'field_56cc0760be371',
				'label' => '页脚社交分享 footer-social-contact',
				'name' => 'footer-social-contact',
				'type' => 'wysiwyg',
				'default_value' => '',
				'toolbar' => 'full',
				'media_upload' => 'yes',
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'page',
					'operator' => '==',
					'value' => '46',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
		),
		'options' => array (
			'position' => 'normal',
			'layout' => 'default',
			'hide_on_screen' => array (
				0 => 'the_content',
				1 => 'excerpt',
				2 => 'custom_fields',
				3 => 'discussion',
				4 => 'comments',
				5 => 'slug',
				6 => 'author',
				7 => 'format',
				8 => 'featured_image',
				9 => 'categories',
				10 => 'tags',
				11 => 'send-trackbacks',
			),
		),
		'menu_order' => 0,
	));
	register_field_group(array (
		'id' => 'acf_%e6%b5%8b%e8%af%95',
		'title' => '测试',
		'fields' => array (
			array (
				'key' => 'field_56c1f4aabea2c',
				'label' => '介绍',
				'name' => 'intro',
				'type' => 'wysiwyg',
				'default_value' => '',
				'toolbar' => 'full',
				'media_upload' => 'yes',
			),
			array (
				'key' => 'field_56c63b9398d3e',
				'label' => '照片',
				'name' => 'photo',
				'type' => 'image',
				'save_format' => 'url',
				'preview_size' => 'full',
				'library' => 'all',
			),
			array (
				'key' => 'field_56c657b348b22',
				'label' => '选择用户',
				'name' => 'user',
				'type' => 'user',
				'role' => array (
					0 => 'administrator',
					1 => 'editor',
					2 => 'author',
					3 => 'contributor',
				),
				'field_type' => 'multi_select',
				'allow_null' => 0,
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'page',
					'operator' => '==',
					'value' => '239',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
		),
		'options' => array (
			'position' => 'normal',
			'layout' => 'no_box',
			'hide_on_screen' => array (
			),
		),
		'menu_order' => 0,
	));
	register_field_group(array (
		'id' => 'acf_%e8%af%a6%e7%bb%86-%e5%8d%9a%e5%ae%a2%e6%96%87%e7%ab%a0',
		'title' => '详细 - 博客文章',
		'fields' => array (
			array (
				'key' => 'field_56c59f7014e84',
				'label' => '封面图片 thumbnail',
				'name' => 'thumbnail',
				'type' => 'image',
				'save_format' => 'url',
				'preview_size' => 'full',
				'library' => 'all',
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'post',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
		),
		'options' => array (
			'position' => 'normal',
			'layout' => 'default',
			'hide_on_screen' => array (
				0 => 'custom_fields',
				1 => 'discussion',
				2 => 'comments',
				3 => 'slug',
				4 => 'format',
				5 => 'featured_image',
			),
		),
		'menu_order' => 0,
	));
	register_field_group(array (
		'id' => 'acf_%e8%af%a6%e7%bb%86-%e5%9b%a2%e9%98%9f%e7%94%a8%e6%88%b7',
		'title' => '详细 - 团队(用户)',
		'fields' => array (
			array (
				'key' => 'field_56c64692a67ce',
				'label' => '头像 profile-picture',
				'name' => 'profile-picture',
				'type' => 'image',
				'instructions' => '图片大小应控制为为317×316。',
				'save_format' => 'url',
				'preview_size' => 'full',
				'library' => 'all',
			),
			array (
				'key' => 'field_56c64800a4e21',
				'label' => '联系电话 phone',
				'name' => 'phone',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => '请输入电话号码',
				'prepend' => '',
				'append' => '',
				'formatting' => 'none',
				'maxlength' => '',
			),
			array (
				'key' => 'field_56c64692dc33a',
				'label' => '对外头衔 titles',
				'name' => 'titles',
				'type' => 'text',
				'default_value' => '领队, 户外专家',
				'placeholder' => '请输入头衔，多个头衔用逗号隔开',
				'prepend' => '',
				'append' => '',
				'formatting' => 'none',
				'maxlength' => '',
			),
			array (
				'key' => 'field_56c648b5a4e22',
				'label' => '内部职位 positions',
				'name' => 'positions',
				'type' => 'checkbox',
				'choices' => array (
					'CEO' => 'CEO',
					'领队' => '领队',
					'职员' => '职员',
					'运营' => '运营',
					'后勤' => '后勤',
					'设计' => '设计',
				),
				'default_value' => '',
				'layout' => 'horizontal',
			),
			array (
				'key' => 'field_56c6ca2373159',
				'label' => '个人介绍 intro',
				'name' => 'intro',
				'type' => 'textarea',
				'default_value' => '',
				'placeholder' => '',
				'maxlength' => '',
				'rows' => '',
				'formatting' => 'br',
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'ef_user',
					'operator' => '==',
					'value' => 'administrator',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
			array (
				array (
					'param' => 'ef_user',
					'operator' => '==',
					'value' => 'editor',
					'order_no' => 0,
					'group_no' => 1,
				),
			),
			array (
				array (
					'param' => 'ef_user',
					'operator' => '==',
					'value' => 'author',
					'order_no' => 0,
					'group_no' => 2,
				),
			),
		),
		'options' => array (
			'position' => 'normal',
			'layout' => 'default',
			'hide_on_screen' => array (
			),
		),
		'menu_order' => 0,
	));
	register_field_group(array (
		'id' => 'acf_%e8%af%a6%e7%bb%86-%e6%88%b7%e5%a4%96%e6%b4%bb%e5%8a%a8',
		'title' => '详细 - 户外活动',
		'fields' => array (
			array (
				'key' => 'field_56c84c18bfd09',
				'label' => '开始时间 date-start',
				'name' => 'date-start',
				'type' => 'date_picker',
				'date_format' => 'yy-mm-dd',
				'display_format' => 'yy-mm-dd',
				'first_day' => 1,
			),
			array (
				'key' => 'field_56c84c5ebfd0a',
				'label' => '结束时间 date-end',
				'name' => 'date-end',
				'type' => 'date_picker',
				'date_format' => 'yy-mm-dd',
				'display_format' => 'yy-mm-dd',
				'first_day' => 1,
			),
			array (
				'key' => 'field_56c1cbd061c1e',
				'label' => '活动封面图 thumbnail',
				'name' => 'thumbnail',
				'type' => 'image',
				'save_format' => 'url',
				'preview_size' => 'full',
				'library' => 'all',
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'outdoors',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
		),
		'options' => array (
			'position' => 'acf_after_title',
			'layout' => 'default',
			'hide_on_screen' => array (
				0 => 'custom_fields',
				1 => 'discussion',
				2 => 'comments',
				3 => 'slug',
				4 => 'author',
				5 => 'format',
				6 => 'featured_image',
				7 => 'send-trackbacks',
			),
		),
		'menu_order' => 0,
	));
	register_field_group(array (
		'id' => 'acf_%e8%af%a6%e7%bb%86-%e6%88%b7%e5%a4%96%e8%a3%85%e5%a4%87',
		'title' => '详细 - 户外装备',
		'fields' => array (
			array (
				'key' => 'field_56c1cd2be5ede',
				'label' => '装备封面图 thumbnail',
				'name' => 'thumbnail',
				'type' => 'image',
				'save_format' => 'url',
				'preview_size' => 'full',
				'library' => 'all',
			),
			array (
				'key' => 'field_56c1ccc6bf25c',
				'label' => '购买链接 order-link',
				'name' => 'order-link',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => '请输入淘宝/京东等站外购买链接.',
				'prepend' => '',
				'append' => '',
				'formatting' => 'none',
				'maxlength' => '',
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'outfits',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
		),
		'options' => array (
			'position' => 'normal',
			'layout' => 'default',
			'hide_on_screen' => array (
				0 => 'the_content',
				1 => 'excerpt',
				2 => 'custom_fields',
				3 => 'discussion',
				4 => 'comments',
				5 => 'slug',
				6 => 'author',
				7 => 'format',
				8 => 'featured_image',
				9 => 'tags',
				10 => 'send-trackbacks',
			),
		),
		'menu_order' => 0,
	));
	register_field_group(array (
		'id' => 'acf_%e8%af%a6%e7%bb%86-%e7%a7%81%e4%ba%ba%e5%ae%9a%e5%88%b6%e6%9c%8d%e5%8a%a1',
		'title' => '详细 - 私人定制服务',
		'fields' => array (
			array (
				'key' => 'field_56c74f4877a43',
				'label' => '展示盒类型 is-promote',
				'name' => 'is-promote',
				'type' => 'radio',
				'choices' => array (
					'' => '普通',
					'pricing-plan-promote' => '高级',
				),
				'other_choice' => 0,
				'save_other_choice' => 0,
				'default_value' => '',
				'layout' => 'horizontal',
			),
			array (
				'key' => 'field_56c64aa4e6cbf',
				'label' => '价格 service-price',
				'name' => 'service-price',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'none',
				'maxlength' => '',
			),
			array (
				'key' => 'field_56c64acae6cc1',
				'label' => '单位 service-price-unit',
				'name' => 'service-price-unit',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'none',
				'maxlength' => '',
			),
			array (
				'key' => 'field_56c64cf09e6ba',
				'label' => '相关链接 service-link',
				'name' => 'service-link',
				'type' => 'page_link',
				'post_type' => array (
					0 => 'outdoors',
				),
				'allow_null' => 0,
				'multiple' => 0,
			),
			array (
				'key' => 'field_56c64b07e6cc3',
				'label' => '按钮文字 service-btn-title',
				'name' => 'service-btn-title',
				'type' => 'text',
				'default_value' => '现在订购',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'none',
				'maxlength' => '',
			),
			array (
				'key' => 'field_56c64b2be6cc4',
				'label' => '贴标文字 service-ribbon-title',
				'name' => 'service-ribbon-title',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'none',
				'maxlength' => 4,
			),
			array (
				'key' => 'field_56c64b57e6cc5',
				'label' => '贴标颜色 service-ribbon-color',
				'name' => 'service-ribbon-color',
				'type' => 'select',
				'choices' => array (
					'' => '',
					'ribbon-green' => '绿色',
					'ribbon-blue' => '蓝色',
					'ribbon-orange' => '橙色',
					'ribbon-red' => '红色',
				),
				'default_value' => '',
				'allow_null' => 0,
				'multiple' => 0,
			),
			array (
				'key' => 'field_56c64c409e6b9',
				'label' => '摘要 service-excerpt',
				'name' => 'service-excerpt',
				'type' => 'textarea',
				'default_value' => '',
				'placeholder' => '',
				'maxlength' => '',
				'rows' => '',
				'formatting' => 'br',
			),
			array (
				'key' => 'field_56c9f81942368',
				'label' => '展示图 service-img',
				'name' => 'service-img',
				'type' => 'image',
				'save_format' => 'url',
				'preview_size' => 'full',
				'library' => 'all',
			),
			array (
				'key' => 'field_56c64adee6cc2',
				'label' => '详情 service-details',
				'name' => 'service-details',
				'type' => 'wysiwyg',
				'default_value' => '',
				'toolbar' => 'full',
				'media_upload' => 'yes',
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'services',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
		),
		'options' => array (
			'position' => 'normal',
			'layout' => 'default',
			'hide_on_screen' => array (
				0 => 'the_content',
				1 => 'excerpt',
				2 => 'custom_fields',
				3 => 'discussion',
				4 => 'comments',
				5 => 'slug',
				6 => 'author',
				7 => 'format',
				8 => 'featured_image',
				9 => 'categories',
				10 => 'tags',
			),
		),
		'menu_order' => 0,
	));
	register_field_group(array (
		'id' => 'acf_%e9%a1%b5%e9%9d%a2-%e5%85%b3%e4%ba%8e%e6%88%91%e4%bb%ac',
		'title' => '页面 - 关于我们',
		'fields' => array (
			array (
				'key' => 'field_56bb2c4659720',
				'label' => '团队合影 banner_photo',
				'name' => 'banner_photo',
				'type' => 'image',
				'instructions' => '图片尺寸应该为947×526。否则会影响显示效果',
				'save_format' => 'url',
				'preview_size' => 'large',
				'library' => 'all',
			),
			array (
				'key' => 'field_56bb2be85971e',
				'label' => '标语-标题 banner_title',
				'name' => 'banner_title',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => '请输入一个标语的标题',
				'prepend' => '',
				'append' => '',
				'formatting' => 'none',
				'maxlength' => '',
			),
			array (
				'key' => 'field_56bb2c285971f',
				'label' => '标语-内容 banner_content',
				'name' => 'banner_content',
				'type' => 'textarea',
				'default_value' => '',
				'placeholder' => '',
				'maxlength' => '',
				'rows' => '',
				'formatting' => 'br',
			),
			array (
				'key' => 'field_56bb2cc059721',
				'label' => '分栏介绍1-标题 intro_title_1',
				'name' => 'intro_title_1',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => '请输入第1栏介绍的标题',
				'prepend' => '',
				'append' => '',
				'formatting' => 'none',
				'maxlength' => 10,
			),
			array (
				'key' => 'field_56bb2d5d59722',
				'label' => '分栏介绍1-内容 intro_content_1',
				'name' => 'intro_content_1',
				'type' => 'textarea',
				'default_value' => '',
				'placeholder' => '',
				'maxlength' => '',
				'rows' => '',
				'formatting' => 'br',
			),
			array (
				'key' => 'field_56bb2e8292fa2',
				'label' => '分栏介绍2-标题 intro_title_2',
				'name' => 'intro_title_2',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => '请输入第1栏介绍的标题',
				'prepend' => '',
				'append' => '',
				'formatting' => 'none',
				'maxlength' => 10,
			),
			array (
				'key' => 'field_56bb2eec92fa6',
				'label' => '分栏介绍2-内容 intro_content_2',
				'name' => 'intro_content_2',
				'type' => 'textarea',
				'default_value' => '',
				'placeholder' => '',
				'maxlength' => '',
				'rows' => '',
				'formatting' => 'br',
			),
			array (
				'key' => 'field_56bb2e8192fa1',
				'label' => '分栏介绍3-标题 intro_title_3',
				'name' => 'intro_title_3',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => '请输入第1栏介绍的标题',
				'prepend' => '',
				'append' => '',
				'formatting' => 'none',
				'maxlength' => 10,
			),
			array (
				'key' => 'field_56bb2eeb92fa5',
				'label' => '分栏介绍3-内容 intro_content_3',
				'name' => 'intro_content_3',
				'type' => 'textarea',
				'default_value' => '',
				'placeholder' => '',
				'maxlength' => '',
				'rows' => '',
				'formatting' => 'br',
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'page',
					'operator' => '==',
					'value' => '118',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
		),
		'options' => array (
			'position' => 'normal',
			'layout' => 'default',
			'hide_on_screen' => array (
				0 => 'the_content',
				1 => 'excerpt',
				2 => 'custom_fields',
				3 => 'discussion',
				4 => 'comments',
				5 => 'slug',
				6 => 'author',
				7 => 'format',
				8 => 'featured_image',
				9 => 'categories',
				10 => 'tags',
			),
		),
		'menu_order' => 0,
	));
	register_field_group(array (
		'id' => 'acf_%e9%a1%b5%e9%9d%a2-%e5%ae%98%e6%96%b9%e5%8d%9a%e5%ae%a2%e5%88%97%e8%a1%a8',
		'title' => '页面 - 官方博客列表',
		'fields' => array (
			array (
				'key' => 'field_56bb42c29aa24',
				'label' => '左侧人物头像 left_editor_photo',
				'name' => 'left_editor_photo',
				'type' => 'image',
				'save_format' => 'url',
				'preview_size' => 'thumbnail',
				'library' => 'all',
			),
			array (
				'key' => 'field_56bb4a5ed1bdc',
				'label' => '左侧人物背景 left_editor_bg',
				'name' => 'left_editor_bg',
				'type' => 'image',
				'save_format' => 'url',
				'preview_size' => 'medium',
				'library' => 'all',
			),
			array (
				'key' => 'field_56bb449d823f0',
				'label' => '左侧人物名称 left_editor_name',
				'name' => 'left_editor_name',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => '请输入名称',
				'prepend' => '',
				'append' => '',
				'formatting' => 'none',
				'maxlength' => 19,
			),
			array (
				'key' => 'field_56bb4aff160b6',
				'label' => '左侧人物介绍 left_editor_intro',
				'name' => 'left_editor_intro',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => '请输入主编的介绍',
				'prepend' => '',
				'append' => '',
				'formatting' => 'none',
				'maxlength' => '',
			),
			array (
				'key' => 'field_56c5c08d37558',
				'label' => '页面类型 post_type',
				'name' => 'post_type',
				'type' => 'select',
				'instructions' => '(程序代码中调用.请不要改动此处!否则将严重影响页面呈现!)',
				'required' => 1,
				'choices' => array (
					'post' => 'post',
					'outdoors' => 'outdoors',
				),
				'default_value' => 'post',
				'allow_null' => 0,
				'multiple' => 0,
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'page',
					'operator' => '==',
					'value' => '65',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
		),
		'options' => array (
			'position' => 'normal',
			'layout' => 'default',
			'hide_on_screen' => array (
				0 => 'the_content',
				1 => 'excerpt',
				2 => 'custom_fields',
				3 => 'discussion',
				4 => 'comments',
				5 => 'slug',
				6 => 'author',
				7 => 'format',
				8 => 'featured_image',
				9 => 'send-trackbacks',
			),
		),
		'menu_order' => 0,
	));
	register_field_group(array (
		'id' => 'acf_%e9%a1%b5%e9%9d%a2-%e6%88%b7%e5%a4%96%e6%b4%bb%e5%8a%a8%e5%88%97%e8%a1%a8',
		'title' => '页面 - 户外活动列表',
		'fields' => array (
			array (
				'key' => 'field_56c856d74aa47',
				'label' => '左侧人物头像 left_editor_photo',
				'name' => 'left_editor_photo',
				'type' => 'image',
				'save_format' => 'url',
				'preview_size' => 'thumbnail',
				'library' => 'all',
			),
			array (
				'key' => 'field_56c856d77cf03',
				'label' => '左侧人物背景 left_editor_bg',
				'name' => 'left_editor_bg',
				'type' => 'image',
				'save_format' => 'url',
				'preview_size' => 'medium',
				'library' => 'all',
			),
			array (
				'key' => 'field_56c856d755629',
				'label' => '左侧人物名称 left_editor_name',
				'name' => 'left_editor_name',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => '请输入名称',
				'prepend' => '',
				'append' => '',
				'formatting' => 'none',
				'maxlength' => 19,
			),
			array (
				'key' => 'field_56c856d78b196',
				'label' => '左侧人物介绍 left_editor_intro',
				'name' => 'left_editor_intro',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => '请输入主编的介绍',
				'prepend' => '',
				'append' => '',
				'formatting' => 'none',
				'maxlength' => '',
			),
			array (
				'key' => 'field_56c856d7a6334',
				'label' => '页面类型 post_type',
				'name' => 'post_type',
				'type' => 'select',
				'instructions' => '(专为程序代码中调用.请不要改动此处!否则将严重影响页面呈现!)',
				'required' => 1,
				'choices' => array (
					'post' => 'post',
					'outdoors' => 'outdoors',
				),
				'default_value' => 'post',
				'allow_null' => 0,
				'multiple' => 0,
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'page',
					'operator' => '==',
					'value' => '195',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
		),
		'options' => array (
			'position' => 'normal',
			'layout' => 'default',
			'hide_on_screen' => array (
				0 => 'the_content',
				1 => 'excerpt',
				2 => 'custom_fields',
				3 => 'discussion',
				4 => 'comments',
				5 => 'slug',
				6 => 'author',
				7 => 'format',
				8 => 'featured_image',
				9 => 'send-trackbacks',
			),
		),
		'menu_order' => 0,
	));
	register_field_group(array (
		'id' => 'acf_%e9%a1%b5%e9%9d%a2-%e6%88%b7%e5%a4%96%e8%a3%85%e5%a4%87%e5%88%97%e8%a1%a8',
		'title' => '页面 - 户外装备列表',
		'fields' => array (
			array (
				'key' => 'field_56c5afd7a6825',
				'label' => '每种一级分类的显示数量 sub-category-count',
				'name' => 'sub-category-count',
				'type' => 'text',
				'instructions' => '根据页面效果选择: 一般一行显示3个,最好是3的倍数.',
				'default_value' => 3,
				'placeholder' => '请输入一个数字',
				'prepend' => '',
				'append' => '',
				'formatting' => 'none',
				'maxlength' => '',
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'page',
					'operator' => '==',
					'value' => '174',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
		),
		'options' => array (
			'position' => 'normal',
			'layout' => 'default',
			'hide_on_screen' => array (
				0 => 'the_content',
				1 => 'custom_fields',
				2 => 'discussion',
				3 => 'comments',
				4 => 'slug',
				5 => 'author',
				6 => 'format',
				7 => 'featured_image',
				8 => 'categories',
				9 => 'tags',
				10 => 'send-trackbacks',
			),
		),
		'menu_order' => 0,
	));
	register_field_group(array (
		'id' => 'acf_%e9%a1%b5%e9%9d%a2-%e7%a7%81%e4%ba%ba%e5%ae%9a%e5%88%b6',
		'title' => '页面 - 私人定制',
		'fields' => array (
			array (
				'key' => 'field_56c8110d3c435',
				'label' => '热门价目单 - 标题 pricing-table-title',
				'name' => 'pricing-table-title',
				'type' => 'text',
				'default_value' => '热门私人定制',
				'placeholder' => '请输入一个标题',
				'prepend' => '',
				'append' => '',
				'formatting' => 'none',
				'maxlength' => '',
			),
			array (
				'key' => 'field_56c811b63c436',
				'label' => '全部价目表 - 标题 pricing-list-title',
				'name' => 'pricing-list-title',
				'type' => 'text',
				'default_value' => '详细价目表',
				'placeholder' => '请输入一个标题',
				'prepend' => '',
				'append' => '',
				'formatting' => 'none',
				'maxlength' => '',
			),
			array (
				'key' => 'field_56c81f93a9491',
				'label' => '对话框头像 pop-box-img',
				'name' => 'pop-box-img',
				'type' => 'image',
				'save_format' => 'url',
				'preview_size' => 'thumbnail',
				'library' => 'all',
			),
			array (
				'key' => 'field_56c8210ca9492',
				'label' => '对话框内容 pop-box-content',
				'name' => 'pop-box-content',
				'type' => 'wysiwyg',
				'default_value' => '',
				'toolbar' => 'full',
				'media_upload' => 'yes',
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'page',
					'operator' => '==',
					'value' => '95',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
		),
		'options' => array (
			'position' => 'acf_after_title',
			'layout' => 'default',
			'hide_on_screen' => array (
				0 => 'the_content',
				1 => 'excerpt',
				2 => 'custom_fields',
				3 => 'discussion',
				4 => 'comments',
				5 => 'slug',
				6 => 'author',
				7 => 'format',
				8 => 'featured_image',
				9 => 'categories',
				10 => 'tags',
				11 => 'send-trackbacks',
			),
		),
		'menu_order' => 0,
	));
	register_field_group(array (
		'id' => 'acf_%e9%a1%b5%e9%9d%a2-%e8%81%94%e7%b3%bb%e6%88%91%e4%bb%ac',
		'title' => '页面 - 联系我们',
		'fields' => array (
			array (
				'key' => 'field_56bdfce353fe4',
				'label' => '联系地址 contactus-address',
				'name' => 'contactus-address',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'none',
				'maxlength' => '',
			),
			array (
				'key' => 'field_56bdfd6353fe7',
				'label' => '电子邮箱 contactus-email',
				'name' => 'contactus-email',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'none',
				'maxlength' => '',
			),
			array (
				'key' => 'field_56bdfd6253fe6',
				'label' => '电话 contactus-phone',
				'name' => 'contactus-phone',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'none',
				'maxlength' => '',
			),
			array (
				'key' => 'field_56c960cc3006a',
				'label' => '传真 contactus-fax',
				'name' => 'contactus-fax',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'none',
				'maxlength' => '',
			),
			array (
				'key' => 'field_56be089e0c906',
				'label' => '地图信息 map-info',
				'name' => 'map-info',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => '请输入地理位置的信息(如怎样到达公司)',
				'prepend' => '',
				'append' => '',
				'formatting' => 'none',
				'maxlength' => '',
			),
			array (
				'key' => 'field_56c826cc57b9c',
				'label' => '地理坐标 map-coordinates',
				'name' => 'map-coordinates',
				'type' => 'text',
				'instructions' => '请输入地图的X,Y坐标. 两个数字用英文逗号分开.',
				'default_value' => '116.335862,40.063215',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'none',
				'maxlength' => '',
			),
			array (
				'key' => 'field_56c95e6b30dc3',
				'label' => '地图(图片形式) map-img',
				'name' => 'map-img',
				'type' => 'image',
				'instructions' => '请插入一张清晰显示地理位置地图',
				'save_format' => 'url',
				'preview_size' => 'full',
				'library' => 'all',
			),
			array (
				'key' => 'field_56cb3dbd5b439',
				'label' => '微信二维码 wechat-qrcode',
				'name' => 'wechat-qrcode',
				'type' => 'image',
				'save_format' => 'url',
				'preview_size' => 'full',
				'library' => 'all',
			),
			array (
				'key' => 'field_56c95dd1ee699',
				'label' => '联络表单 contactus-form',
				'name' => 'contactus-form',
				'type' => 'wysiwyg',
				'instructions' => '请插入一个表单.',
				'default_value' => '',
				'toolbar' => 'full',
				'media_upload' => 'yes',
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'page',
					'operator' => '==',
					'value' => '62',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
		),
		'options' => array (
			'position' => 'normal',
			'layout' => 'default',
			'hide_on_screen' => array (
				0 => 'the_content',
				1 => 'excerpt',
				2 => 'custom_fields',
				3 => 'discussion',
				4 => 'comments',
				5 => 'slug',
				6 => 'author',
				7 => 'format',
				8 => 'featured_image',
				9 => 'categories',
				10 => 'tags',
				11 => 'send-trackbacks',
			),
		),
		'menu_order' => 0,
	));
	register_field_group(array (
		'id' => 'acf_%e9%a1%b5%e9%9d%a2-%e9%a6%96%e9%a1%b5',
		'title' => '页面 - 首页',
		'fields' => array (
			array (
				'key' => 'field_56c85bdccc8eb',
				'label' => '巨幕',
				'name' => '',
				'type' => 'tab',
			),
			array (
				'key' => 'field_56c0e456b7b43',
				'label' => '首页大背景 bg_img',
				'name' => 'bg_img',
				'type' => 'image',
				'save_format' => 'url',
				'preview_size' => 'full',
				'library' => 'all',
			),
			array (
				'key' => 'field_56bc2b75c8b90',
				'label' => '大标题 slider_title',
				'name' => 'slider_title',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => '请输入大标题',
				'prepend' => '',
				'append' => '',
				'formatting' => 'none',
				'maxlength' => '',
			),
			array (
				'key' => 'field_56bc2e13c8b91',
				'label' => '副标题1 subtitle_1',
				'name' => 'subtitle_1',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'none',
				'maxlength' => '',
			),
			array (
				'key' => 'field_56bc2e8bc8b95',
				'label' => '副标题2 subtitle_2',
				'name' => 'subtitle_2',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'none',
				'maxlength' => '',
			),
			array (
				'key' => 'field_56bc2e8ac8b94',
				'label' => '副标题3 subtitle_3',
				'name' => 'subtitle_3',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'none',
				'maxlength' => '',
			),
			array (
				'key' => 'field_56bc2fa48a218',
				'label' => '标语内容 intro',
				'name' => 'intro',
				'type' => 'textarea',
				'default_value' => '',
				'placeholder' => '请输入一段引人入胜的介绍',
				'maxlength' => '',
				'rows' => 2,
				'formatting' => 'br',
			),
			array (
				'key' => 'field_56bc3027c8001',
				'label' => '标语按钮文字 banner_btn',
				'name' => 'banner_btn',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => '请输入一个名称作为按钮上显示的文字',
				'prepend' => '',
				'append' => '',
				'formatting' => 'none',
				'maxlength' => '',
			),
			array (
				'key' => 'field_56c85c0ccc8ec',
				'label' => '标语按钮链接 banner_btn_link',
				'name' => 'banner_btn_link',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'none',
				'maxlength' => '',
			),
			array (
				'key' => 'field_56c5cdc7f6794',
				'label' => '企业介绍',
				'name' => '',
				'type' => 'tab',
			),
			array (
				'key' => 'field_56bc30cb55233',
				'label' => '企业介绍标题 corp_intro_title',
				'name' => 'corp_intro_title',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => '请输入一个题目',
				'prepend' => '',
				'append' => '',
				'formatting' => 'none',
				'maxlength' => '',
			),
			array (
				'key' => 'field_56bc311055234',
				'label' => '企业介绍内容 corp_intro_content',
				'name' => 'corp_intro_content',
				'type' => 'wysiwyg',
				'default_value' => '',
				'toolbar' => 'full',
				'media_upload' => 'no',
			),
			array (
				'key' => 'field_56bc312b55235',
				'label' => '企业介绍图像 corp_intro_img',
				'name' => 'corp_intro_img',
				'type' => 'image',
				'save_format' => 'url',
				'preview_size' => 'full',
				'library' => 'all',
			),
			array (
				'key' => 'field_56c85c44cc8ed',
				'label' => '首页团队展示',
				'name' => '',
				'type' => 'tab',
			),
			array (
				'key' => 'field_56c65e2e1dbb0',
				'label' => '4名团队成员 team',
				'name' => 'team',
				'type' => 'user',
				'instructions' => '请用Ctrl键,选择4个团队成员信息,登上首页展示',
				'role' => array (
					0 => 'administrator',
					1 => 'editor',
					2 => 'author',
				),
				'field_type' => 'multi_select',
				'allow_null' => 0,
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'page',
					'operator' => '==',
					'value' => '46',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
		),
		'options' => array (
			'position' => 'normal',
			'layout' => 'default',
			'hide_on_screen' => array (
				0 => 'the_content',
				1 => 'excerpt',
				2 => 'custom_fields',
				3 => 'discussion',
				4 => 'comments',
				5 => 'slug',
				6 => 'author',
				7 => 'format',
				8 => 'featured_image',
				9 => 'categories',
				10 => 'tags',
			),
		),
		'menu_order' => 0,
	));
}


/*>>>>>>>>>>>>>>End of File>>>>>>>>>>>>>>>>>*/
 ?>